version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app  # 경로에서 'ec2-user'를 'ubuntu'로 변경

permissions:
  - object: /home/ubuntu/app
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root 
  AfterInstall:
    - location: scripts/after_install.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_server.sh
      runas: ubuntu
